version: '3'
services:
  shop_api:
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "7001:8000"
    depends_on:
      - shop_api_db
  shop_api_db:
    image: "postgres:14"
    environment:
      - POSTGRES_DB=products_gk_kg
      - POSTGRES_USER=products_gk_kg_user
      - POSTGRES_PASSWORD=20092009
    volumes:
      - 'shop_api-data:/var/lib/postgresql/data'
volumes:
  shop_api-data: